name: "Contribute List"
description: "Automation of contributors list in README.md"
inputs:
    image_size:
        description: "Size of square images in the stack"
        required: false
        default: "100"
    readme_path:
        description: "Path of the readme file you want to update"
        default: "README.md"
        required: false
    use_username:
        description: "To use github-id instead of profile name"
        default: "false"
        required: false
    columns_per_row:
        description: "Number of columns in a row"
        required: false
        default: "6"
    collaborators:
        description: "Type of collaborators options: all/direct/outside"
        required: false
        default: "direct"
    commit_message:
        description: "Commit message of the github action"
        default: "contrib-readme-action has updated readme"
        required: false
    committer_username:
        description: "Username on commit"
        required: false
    committer_email:
        description: "email id of committer"
        required: false
    pr_title_on_protected:
        description: "Title of the PR that will be created if the branch is protected"
        default: "contributors readme action update"
        required: false
outputs:
    pr_id: # id of pr
        description: "Id of the generated PR when the branch is in protected mode"
runs:
    using: "node12"
    main: "dist/index.js"
branding:
    icon: "archive"
    color: "yellow"
