export default `
query {
    user(login: "freakboy3742") {
        name
        sponsorshipsAsMaintainer(first: 100) {
            nodes {
                sponsorEntity {
                    ... on User {
                        name
                        login
                        avatarUrl
                    }
                }
            }
        }
    }
}
`
